Section "InputClass"
    Identifier         "touchscreen"
    MatchIsTouchscreen "on"
    Driver             "evdev"
    Option             "EmulateThirdButton"              "1"
    Option             "EmulateThirdButtonTimeout"       "750"
    Option             "EmulateThirdButtonMoveThreshold" "30"
EndSection
