Section "Device"
    Identifier "LCD"
    Driver     "fbdev"
    Option     "fbdev" "/dev/fb1"
EndSection

Section "Monitor"
    Identifier "LCD"
    Option     "DPMS" "false"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device     "LCD"
    Monitor    "LCD"
    DefaultDepth 16
    SubSection "Display"
        Depth  16
        Modes  "480x320"
    EndSubSection
EndSection

Section "ServerLayout"
    Identifier "Layout0"
    Screen     "Screen0"
EndSection
